### ISSUE TITLE
Send Customized Patch List

### ISSUE THREAD

**Issue by SimonOmega** [SimonOmega/UOPatchServer#4]
Send Customized Patch List to clients based on their reported versions.

**Comment by Nylar1971** [comment]
woohoo :)

**Comment by SimonOmega** [comment]
Every rtp patch file had a matching pat file.  The pat file is used to map patch name to a game version.  Example `uosa_win32_7-0-11-0.pat` will map `uosa_win32_7-0-11-0.rtp` to `Win32_UOSA 33` which is client Win32 UO SA version 33.  This becomes a lot easier to send patches as long as you have the pat and rtp files both.  It is a nightmare to figure it out without the pat file.  But you can create pat files in any text editor.  So I will write this expecting the pat files, as they are easily created.

**Comment by SimonOmega** [comment]
I was under the impression the Client needed all the required patches sent in the patch list.  I think this is wrong.  It seems to be the following.
Client reports it's version until the Server sends a patch list.  
It asks for each file in the patch list.
Reporting it's version after each file.

TODO:
1. Catch the first version reported.
2. Send the list with rtp first and pat second.
3. Let the client keep reporting it's version.
4. When the client finally reports it has the new version send the next patch list.
5. Repeat for all patches required.

I currently have it shoving every pat and ever rtp file into the patch list.  And have it sending a patch list every time a version is reported.  Client gets confused and dies.

I did not notice this communication in the old sequential server, but this new class based server is allowing me to see all the messages.  Good or bad, it is what it is.  I will get to patching it.

**Comment by SimonOmega** [comment]
Been in class and working.  Still in progress...  If I think, patches should be sent one at a time.  It seems the Client responds with the new version once patched.  So The server should be able to step one at a time.  I'm just going to base it off a Dictionary and walk the patches from the clients version up to the max offering of the server.

Windows updated and killed my mouse.  Fedora is installing Workstation 21 so no git updates tonight.

**Comment by SimonOmega** [comment]
Still need testing and clean up.  All calculated from server side and patch list created via difference in Client Reported Version and Available Archive.

 CLIENT >> 127.0.0.1 sent Client Hello/Request (b'\x00\x00\x00\x15')



Server Sending: Protocol, Command, and UseSelf


CLIENT >> 127.0.0.1 sent Version Information Win32_UOSA 34

PATCH LIST BABY

SERVER << sent 127.0.0.1 PatchListData entry {'patname': b'uosa_win32_7-0-11-1.pat', 'patnamelen': b'\x00\x00\x00\x17', 'rtpnamelen': b'\x00\x00\x00\x17', 'patlen': b'\x00\x00\x00\r', 'rtpname': b'uosa_win32_7-0-11-1.rtp', 'rtplen': b'\x03s\xa4\x8e'}


SERVER << sent 127.0.0.1 PatchListData entry {'patname': b'uosa_win32_7-0-11-2.pat', 'patnamelen': b'\x00\x00\x00\x17', 'rtpnamelen': b'\x00\x00\x00\x17', 'patlen': b'\x00\x00\x00\r', 'rtpname': b'uosa_win32_7-0-11-2.rtp', 'rtplen': b'\x03\xb76b'}


SERVER << sent 127.0.0.1 PatchListData entry {'patname': b'uosa_win32_7-0-11-3.pat', 'patnamelen': b'\x00\x00\x00\x17', 'rtpnamelen': b'\x00\x00\x00\x17', 'patlen': b'\x00\x00\x00\r', 'rtpname': b'uosa_win32_7-0-11-3.rtp', 'rtplen': b'\x07\xdc\xc7\x1a'}


SERVER << sent 127.0.0.1 PatchListData entry {'patname': b'uosa_win32_7-0-11-4.pat', 'patnamelen': b'\x00\x00\x00\x17', 'rtpnamelen': b'\x00\x00\x00\x17', 'patlen': b'\x00\x00\x00\r', 'rtpname': b'uosa_win32_7-0-11-4.rtp', 'rtplen': b'\x03tnC'}


CLIENT >> 127.0.0.1 sent a Request for File uosa_win32_7-0-11-1.pat ({'padding': 0, 'working_filename': 'uosa_win32_7-0-11-1.pat', 'namelen': 23})

**Comment by SimonOmega** [comment]
Server generates patch list.
